/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'amrish' at '8/22/16 11:04 PM' with Gradle 3.0
 *
 * @author amrish, @date 8/22/16 11:04 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
